import { createSlice } from '@reduxjs/toolkit';
import { decreaseGuestLogic, incresaeGuestLogic } from './eventFunction';


const initialState = {
  // menuTitle:"Main menu",
  searchPlaceholder:"Search Menu Item",
  orderTitle:"Your order",
  subtotalText:"Subtotal:",
  discountText:"Tip",
  totaltext:"Total",
  orderSliderButtonText:"Close",
  orderSliderTitleText:"Your order was successfully placed",
  orderSliderdescriptionText:"Your order was successfully placed",
  guestCount:1
};

// changeSelectedKategoriType
export const productSlice = createSlice({
  name: 'product',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    decreaseGuest:decreaseGuestLogic,
    incresaeGuest:incresaeGuestLogic,

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
   
  },
});

export const {createSliderPacket,decreaseGuest,incresaeGuest } = productSlice.actions;
export default productSlice.reducer;