import { createSlice } from '@reduxjs/toolkit';
import { getHomeDetails } from '../../Api/Branch/getApi';
import { fetchGaleryImg } from '../../Api/fetchGalleryData/fetchGaleryImg';
import { getHomedetailLogic } from './asyncSliceLogic';
import { splitImgToArray,openSliderLogic,closeGallerySliderLogic, openPaymentPopUpLogic, chengpaymenMethodLogic, openRaitPopUpLogic, rateRestourantLogic, homeScrollTopLogic } from './sliceLogic';

const initialState = {
  titleLogoUrl:"/images/home/logoTitle.png",
  mainCover:"",
  menyuName:"Our Menu",
  logoUrl:"",
  descriptionName:"",
  descriptionContent:"",
  qrBranchMenu:[
    { id:`${Date.now()}${Math.random()}`, name:"Main Menu", selected:true },
    { id:`${Date.now()}${Math.random()}`, name:"Alkohol Menu", selected:false }
  ],
  galeryState:[
    // [
    //   {url:"/images/home/img0.png"},
    //   {url:"/images/home/img1.png"},
    //   {url:"/images/home/img2.png"},
    //   {url:"/images/home/img3.png"},
    //   {url:"/images/home/img4.png"},
    //   {url:"/images/home/img5.png"}
    // ],
    // [
    //   {url:"/images/home/img0.png"},
    //   {url:"/images/home/img1.png"},
    //   {url:"/images/home/img2.png"},
    //   {url:"/images/home/img3.png"},
    //   {url:"/images/home/img4.png"},
    //   {url:"/images/home/img5.png"}
    // ]
  ],
  gallerySlider:[],
  SliderKey:false,





  // Api kcvac chi
  homeScrollbutton:false,
  notNowRateFeetback:"Not this time",
  placeholderRate:"Rate Review",
  rateKey:false,
  rateTitle:"Please rate us",
  rateDescription:"We are very thankful for using our service. Please rate our service for further service improving",
  RateData:[
    {id:`${Date.now()}${Math.random()}`,selected:false},
    {id:`${Date.now()}${Math.random()}`,selected:false},
    {id:`${Date.now()}${Math.random()}`,selected:false},
    {id:`${Date.now()}${Math.random()}`,selected:false},
    {id:`${Date.now()}${Math.random()}`,selected:false}
  ],
  paymenMethodData:[
    {id:`${Date.now()}${Math.random()}`,name:"Cash",selected:false},
    {id:`${Date.now()}${Math.random()}`,name:"POS terminal",selected:false}
  ],
  paymentTitle:"Choose payment method",
  paymentChooseButton:"Choose",
  paymentMethodKey:false,
  payOnlineText:"Pay online",
  AskForBill:"Ask for bill",
  viewDetailButtonText:"view details",
  detailOrderTotalText:"Total:",
  orderItemText:"items ordered",
  shimmerLoading:true,
  galleryName:"Restaurant gallery",
};


export const homeSlice = createSlice({
  name: 'home',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    openSlider:openSliderLogic,
    closeGallerySlider:closeGallerySliderLogic,
    openPaymentPopUp:openPaymentPopUpLogic,
    chengpaymenMethod:chengpaymenMethodLogic,
    openRaitPopUp:openRaitPopUpLogic,
    rateRestourant:rateRestourantLogic,
    homeScrollTop:homeScrollTopLogic
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
    .addCase(fetchGaleryImg.pending,(state,action) => {
      // state.shimmerLoading = true
    })
    .addCase(fetchGaleryImg.fulfilled,(state,action) => {
      debugger
      state.shimmerLoading = false
      state.galeryState = splitImgToArray(action)
      // state.gallerySlider = action.payload.hits
    })
    .addCase(getHomeDetails.pending,(state,action) => {
      console.log("getHomeDetails"," -> pending");
    })
    .addCase(getHomeDetails.fulfilled,getHomedetailLogic)
  },
});


export const {
  openSlider,closeGallerySlider,openPaymentPopUp,homeScrollTop,
  chengpaymenMethod,openRaitPopUp,rateRestourant
} = homeSlice.actions;
export default homeSlice.reducer;