import { createSlice } from '@reduxjs/toolkit';
import { fetchGaleryImg } from '../../Api/fetchGalleryData/fetchGaleryImg';
import { splitImgToArray,openSliderLogic,closeGallerySliderLogic, openPaymentPopUpLogic, chengpaymenMethodLogic, openRaitPopUpLogic, rateRestourantLogic, homeScrollTopLogic } from './sliceLogic';

const initialState = {
  homeScrollbutton:false,
  notNowRateFeetback:"Not this time",
  placeholderRate:"Rate Review",
  rateKey:false,
  rateTitle:"Please rate us",
  rateDescription:"We are very thankful for using our service. Please rate our service for further service improving",
  RateData:[
    {id:`${Date.now()}${Math.random()}`,selected:false},
    {id:`${Date.now()}${Math.random()}`,selected:false},
    {id:`${Date.now()}${Math.random()}`,selected:false},
    {id:`${Date.now()}${Math.random()}`,selected:false},
    {id:`${Date.now()}${Math.random()}`,selected:false}
  ],
  paymenMethodData:[
    {id:`${Date.now()}${Math.random()}`,name:"Cash",selected:false},
    {id:`${Date.now()}${Math.random()}`,name:"POS terminal",selected:false}
  ],
  paymentTitle:"Choose payment method",
  paymentChooseButton:"Choose",
  paymentMethodKey:false,
  galeryState:[
    // [
    //   {url:"/images/home/img0.png"},
    //   {url:"/images/home/img1.png"},
    //   {url:"/images/home/img2.png"},
    //   {url:"/images/home/img3.png"},
    //   {url:"/images/home/img4.png"},
    //   {url:"/images/home/img5.png"}
    // ],
    // [
    //   {url:"/images/home/img0.png"},
    //   {url:"/images/home/img1.png"},
    //   {url:"/images/home/img2.png"},
    //   {url:"/images/home/img3.png"},
    //   {url:"/images/home/img4.png"},
    //   {url:"/images/home/img5.png"}
    // ]
  ],
  SliderKey:false,
  gallerySlider:[],
  payOnlineText:"Pay online",
  AskForBill:"Ask for bill",
  viewDetailButtonText:"view details",
  detailOrderTotalText:"Total:",
  orderItemText:"items ordered",
  shimmerLoading:true,
  titleLogoUrl:"/images/home/logoTitle.png",
  logoUrl:"/images/home/logo.png",
  menyuName:"Our Menu",
  homeImg:"/images/home/homeImg.png",
  descriptionName:"About restaurant",
  galleryName:"Restaurant gallery",
  descriptionContent:`Lorem ipsum dolor sit amet,
  consectetur adipiscing elit,
  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru
  Lorem ipsum dolor sit amet,
  consectetur adipiscing elit,
  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
  `,
};


export const homeSlice = createSlice({
  name: 'home',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    openSlider:openSliderLogic,
    closeGallerySlider:closeGallerySliderLogic,
    openPaymentPopUp:openPaymentPopUpLogic,
    chengpaymenMethod:chengpaymenMethodLogic,
    openRaitPopUp:openRaitPopUpLogic,
    rateRestourant:rateRestourantLogic,
    homeScrollTop:homeScrollTopLogic
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
    .addCase(fetchGaleryImg.pending,(state,action) => {
      // state.shimmerLoading = true
    })
    .addCase(fetchGaleryImg.fulfilled,(state,action) => {
      state.shimmerLoading = false
      state.galeryState = splitImgToArray(action)
      state.gallerySlider = action.payload.hits
    })
  },
});


export const {
  openSlider,closeGallerySlider,openPaymentPopUp,homeScrollTop,
  chengpaymenMethod,openRaitPopUp,rateRestourant
} = homeSlice.actions;
export default homeSlice.reducer;