import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {
  siteName:"QR Menu",
  url:"qr-menu.com"
};


export const headerSlice = createSlice({
  name: 'header',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    
  },
});

export const {  } = headerSlice.actions;
export default headerSlice.reducer;
